In [1]:
import numpy as np

### Q.1 Write a function so that the columns of the output matrix are powers of the input vector.

In [7]:
a = np.array([2,3,4])

In [8]:
b = np.array([2,3,4,5,6])

In [10]:
print(a)
print(b)

[2 3 4]
[2 3 4 5 6]


In [11]:
def my_vander_matrix(vector, n , increasing = False):
    
    if not increasing:
        op_matrix = np.array([x**(n-1-i) for x in vector for i in range(n)]).reshape(vector.size,n)
    elif increasing:
        op_matrix = np.array([(x**i) for x in vector for i in range(n)]).reshape(vector.size,n)
    return op_matrix        

In [13]:
print('Output for the First Array\n')

op_matrix_decreasing_order = my_vander_matrix(a,3,False)
op_matrix_increasing_order = my_vander_matrix(a,3,True)

print("Vander matrix of the input array in decreasing order of powers:\n\n",op_matrix_decreasing_order,"\n")
print("Vander matrix of the input array in increasing order of powers:\n\n",op_matrix_increasing_order,"\n")

Output for the First Array

Vander matrix of the input array in decreasing order of powers:

 [[ 4  2  1]
 [ 9  3  1]
 [16  4  1]] 

Vander matrix of the input array in increasing order of powers:

 [[ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]] 



In [14]:
print('Output for the First Array\n')

op_matrix_decreasing_order = my_vander_matrix(b,5,False)
op_matrix_increasing_order = my_vander_matrix(b,5,True)

print("Vander matrix of the input array in decreasing order of powers:\n\n",op_matrix_decreasing_order,"\n")
print("Vander matrix of the input array in increasing order of powers:\n\n",op_matrix_increasing_order,"\n")

Output for the First Array

Vander matrix of the input array in decreasing order of powers:

 [[  16    8    4    2    1]
 [  81   27    9    3    1]
 [ 256   64   16    4    1]
 [ 625  125   25    5    1]
 [1296  216   36    6    1]] 

Vander matrix of the input array in increasing order of powers:

 [[   1    2    4    8   16]
 [   1    3    9   27   81]
 [   1    4   16   64  256]
 [   1    5   25  125  625]
 [   1    6   36  216 1296]] 



### Write a function to find moving average in an array over a window:
### Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [21]:
def my_ma_func(list,k):
    cumsum, moving_avgs = [0],[]
    for i, x in enumerate(list,1):
        cumsum.append(cumsum[i-1] + x)
        if i >= k:
            moving_avg = round(((cumsum[i] - cumsum[i - k])/k),2)
            moving_avgs.append(moving_avg)
    print("Moving average values list:",moving_avgs)
    print("Length of the list n-k+1:", len(moving_avgs))

In [22]:
list = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]

k = 3

my_ma_func(list,k)

Moving average values list: [5.0, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84.0, 93.33, 116.33]
Length of the list n-k+1: 11
